---
username: tonyampomah
composer_home_owner: tonyampomah
composer_home_group: tonyampomah

repo:
  - org
  # - dotfiles
  - dev-machine-playbook

repo_arksolutions_it:
  - arksolutions.it
  - arksolutions.it-finance
  - arksolutions.it-proxy
  - base-next-js
  - base-strapi
  - module-strapi
  - newearswickmobility.co.uk
  - responsively-app
  - strapi-plugin-permalinks
  - tableplus

homebrew_installed_packages:
  # - roots/tap/trellis-cli
  - aspell
  - autoconf
  - automake
  - awscli
  - browserpass
  - cmake
  - composer
  - coreutils
  - editorconfig
  - emacs-plus
  - fd
  - font-cascadia-code
  - font-noto-sans
  - fzf
  - git
  - global
  - glslang
  - gnu-tar
  - go
  - isync
  - jq
  - ledger
  - libvterm
  - markdown
  - mu
  - pandoc
  - pass
  - pkg-config
  - poppler
  - readline
  - ripgrep
  - sbcl
  - sqlite
  - stow
  - wget
  - fnm
  - fastfetch

homebrew_taps: []

homebrew_cask_appdir: /Applications

homebrew_cask_apps:
  - alfred
  - appcleaner
  - audacity
  - balenaetcher
  - calibre
  - docker
  - font-cantarell
  - gimp
  - google-chrome
  - logi-options+
  - kitty
  - mactex
  - mixxx
  - nextcloud
  - obs
  - responsively
  - screaming-frog-seo-spider
  - slack
  - stoplight-studio
  - tableplus
  - vagrant
  - vlc
  - whatsapp
  - zoom

pip_packages:
  - name: robotframework-lsp
    state: present
