---
username: tonyampomah
composer_home_owner: tonyampomah
composer_home_group: tonyampomah

dotfiles_repo: "git@github.com:kwame-dat/dotfiles.git"
dotfiles_repo_version: main
dotfiles_repo_local_destination: "~/Repo/2Areas/dotfiles"

homebrew_installed_packages:
  - aspell
  - autoconf
  - automake
  - awscli
  - browserpass
  - cmake
  - composer
  - coreutils
  - editorconfig
  - emacs-plus
  - fd
  - fzf
  - git
  - global
  - glslang
  - gnu-tar
  - go
  - isync
  - jq
  - ledger
  - libvterm
  - markdown
  - mu
  - neofetch
  - node
  - nvm
  - pandoc
  - pass
  - pkg-config
  - poppler
  - readline
  - ripgrep
  - roots/tap/trellis-cli
  - sbcl
  - sqlite
  - stow
  - wget

homebrew_taps: []

homebrew_cask_appdir: /Applications

homebrew_cask_apps:
  - alacritty
  - alfred
  - appcleaner
  - audacity
  - balenaetcher
  - calibre
  - docker
  - font-cantarell
  - gimp
  - google-chrome
  - logitech-options
  - mactex
  - microsoft-remote-desktop
  - mixxx
  - nextcloud
  - obs
  - responsively
  - screaming-frog-seo-spider
  - slack
  - stoplight-studio
  - tableplus
  - vagrant
  - vlc
  - whatsapp
  - zoom
