---
general_packages:
  # - {name: libreoffice-fresh, state: present}
  # - {name: mpd, state: present}
  # - {name: slack-desktop, state: present}
  # - {name: teams, state: present}
  # - {name: zoom, state: present}
  - {name: android-file-transfer, state: present}
  - {name: audacity, state: present}
  - {name: blender, state: present}
  - {name: calibre, state: present}
  - {name: freerdp, state: present}
  - {name: gimp, state: present}
  - {name: guvcview, state: present}
  - {name: kdenlive, state: present}
  - {name: lmms, state: present}
  - {name: mpc, state: present}
  - {name: mpv, state: present}
  - {name: nextcloud-client, state: present}
  - {name: remmina, state: present}
  - {name: youtube-dl, state: present}

general_aur_packages: []
