---
- name: Include distribution and version-specific vars.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      skip: true

- name: Install Dev Tools
  package:
    name: "{{ item.name }}"
    state: "{{ item.state}}"
  with_items: "{{ dev_tools_packages }}"

- name: Install Dev Tools Aur
  kewlfft.aur.aur:
    use: yay
    name: "{{ item.name }}"
    state: "{{ item.state}}"
  with_items: "{{ dev_tools_aur_packages }}"
  become_user: "{{username}}"
